/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.cesjf.lpiu.interfaces;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author pedro
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMCadCarro = new javax.swing.JMenuItem();
        btVinculos = new javax.swing.JMenuItem();
        jmCadPessoa = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Gerenciamento de Veiculos");

        jMenu1.setText("Controle");

        jMCadCarro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMCadCarro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/cesjf/lpiu/Icons/imagens/icIncluirItem.png"))); // NOI18N
        jMCadCarro.setText("Cadastro de Carros");
        jMCadCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMCadCarroActionPerformed(evt);
            }
        });
        jMenu1.add(jMCadCarro);

        btVinculos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        btVinculos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/cesjf/lpiu/Icons/imagens/icFecharVenda.png"))); // NOI18N
        btVinculos.setText("Cadastro de Vinculos");
        btVinculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVinculosActionPerformed(evt);
            }
        });
        jMenu1.add(btVinculos);

        jmCadPessoa.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        jmCadPessoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/cesjf/lpiu/Icons/imagens/icIncluirCliente.png"))); // NOI18N
        jmCadPessoa.setText("Cadastro de Pessoas");
        jmCadPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCadPessoaActionPerformed(evt);
            }
        });
        jMenu1.add(jmCadPessoa);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ajuda");

        jMSobre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/cesjf/lpiu/Icons/imagens/icCadlivro.png"))); // NOI18N
        jMSobre.setText("Sobre");
        jMSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMSobreActionPerformed(evt);
            }
        });
        jMenu2.add(jMSobre);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMCadCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMCadCarroActionPerformed
        CadCarro cadcar = new CadCarro();
        cadcar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMCadCarroActionPerformed

    private void jMSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMSobreActionPerformed
      LocalDateTime ldt = LocalDateTime.now();
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd' do 'M' de 'yyyy' - 'HH':'mm' hrs'");
        JOptionPane.showMessageDialog(null, "Autor: \n Pedro Augusto"+ "\n Data e hora atual: " + ldt.format(formato));
    }//GEN-LAST:event_jMSobreActionPerformed

    private void jmCadPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCadPessoaActionPerformed
        CadPessoa cadpessoa = new CadPessoa();
        cadpessoa.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jmCadPessoaActionPerformed

    private void btVinculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVinculosActionPerformed
        RegistroCarro regCarro = new RegistroCarro();
        regCarro.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btVinculosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btVinculos;
    private javax.swing.JMenuItem jMCadCarro;
    private javax.swing.JMenuItem jMSobre;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jmCadPessoa;
    // End of variables declaration//GEN-END:variables
}
