/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.cesjf.lpiu.interfaces;

import Classes.Automovel;
import Classes.Pessoa;
import Classes.Vinculo;
import br.cesjf.lpiu.arquivos.ArquivoInCarro;
import br.cesjf.lpiu.arquivos.ArquivoInPessoa;
import br.cesjf.lpiu.arquivos.ArquivoInVinculo;
import br.cesjf.lpiu.arquivos.ArquivoOutCarro;
import br.cesjf.lpiu.arquivos.ArquivoOutPessoa;
import br.cesjf.lpiu.arquivos.ArquivoOutVinculo;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pedro Augusto
 */
public class RegistroCarro extends javax.swing.JFrame {

    private ArquivoInPessoa arqin = new ArquivoInPessoa();
    private Pessoa pessoa = null;
    int linha;
    private ArquivoOutPessoa arqout = new ArquivoOutPessoa();
    
    private ArquivoInCarro arqin2 = new ArquivoInCarro();
    private Automovel car = null;
    int linha2;
    private ArquivoOutCarro arqout2 = new ArquivoOutCarro();
    
    private ArquivoInVinculo arqin3 = new ArquivoInVinculo();
    private Vinculo vinculo = null;
    private ArquivoOutVinculo arqout3 = new ArquivoOutVinculo();
    /**
     * Creates new form RegistroCarro
     */
    public RegistroCarro() {
        vinculo = new Vinculo();
        try {
            arqout3.abrir();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(RegistroCarro.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(RegistroCarro.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtPessoa = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtCarro = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtVinculo = new javax.swing.JTable();
        jbVincular = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jtPessoa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nome", "CPF"
            }
        ));
        jtPessoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtPessoaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtPessoa);

        jtCarro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Placa", "Modelo"
            }
        ));
        jScrollPane2.setViewportView(jtCarro);

        jtVinculo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nome", "Marca"
            }
        ));
        jScrollPane3.setViewportView(jtVinculo);

        jbVincular.setText("Vincular");
        jbVincular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbVincularMouseClicked(evt);
            }
        });
        jbVincular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVincularActionPerformed(evt);
            }
        });

        jButton2.setText("Desvincular");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbVincular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(layout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(47, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jbVincular)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        int cont = 1;

        List<Pessoa> listapessoa = new ArrayList<Pessoa>();

        listapessoa = arqin.getTodasPessoas();
        DefaultTableModel modelopessoa = (DefaultTableModel) jtPessoa.getModel();

        for (int i = jtPessoa.getRowCount() - 1;
                i >= 0; --i) {
            modelopessoa.removeRow(i);
        }

        for (int i = 0;
                i < listapessoa.size();
                i++) {
            modelopessoa.addRow(listapessoa.get(i).getpessoa());
            cont++;
        }
        
        int cont2 = 1;

        List<Automovel> listacar = new ArrayList<Automovel>();

        listacar = arqin2.getTodosCarros();
        DefaultTableModel modelocarro = (DefaultTableModel) jtCarro.getModel();

        for (int i = jtCarro.getRowCount() - 1; i >= 0; --i) {
            modelocarro.removeRow(i);
        }

        for (int i = 0; i < listacar.size(); i++) {
            modelocarro.addRow(listacar.get(i).getcarro());
            cont++;
        }
        
        int cont3 = 1;

        List<Vinculo> listavinculo = new ArrayList<Vinculo>();

        listavinculo = arqin3.getTodosVinculos();
        DefaultTableModel modelovinculo = (DefaultTableModel) jtVinculo.getModel();

        for (int i = jtVinculo.getRowCount() - 1; i >= 0; --i) {
            modelovinculo.removeRow(i);
        }

        for (int i = 0; i < listavinculo.size(); i++) {
            modelovinculo.addRow(listavinculo.get(i).getvinculo());
            cont++;
        }
    }//GEN-LAST:event_formWindowOpened

    private void jtPessoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtPessoaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jtPessoaMouseClicked

    private void jbVincularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbVincularMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbVincularMouseClicked

    private void jbVincularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVincularActionPerformed
        vinculo = new Vinculo();
        
        linha = jtPessoa.getSelectedRow();
        linha2 = jtCarro.getSelectedRow();

        vinculo.getPes().setNome(jtPessoa.getValueAt(linha, 0).toString());
        vinculo.getPes().setCpf(jtPessoa.getValueAt(linha, 1).toString());
        vinculo.getAuto().setPlaca(jtCarro.getValueAt(linha2, 0).toString());
        vinculo.getAuto().setModelo(jtCarro.getValueAt(linha2, 1).toString());
        
        try {
            arqout3.Adicionar(vinculo);
        } catch (IOException ex) {
            Logger.getLogger(CadPessoa.class
                .getName()).log(Level.SEVERE, null, ex);
        }

        JOptionPane.showMessageDialog(
            null, "Vinculo cadastrado com sucesso!");
      

        int cont = 1;

        List<Vinculo> listavinculo = new ArrayList<Vinculo>();

        listavinculo = arqin3.getTodosVinculos();
        DefaultTableModel modelovinculo = (DefaultTableModel) jtVinculo.getModel();

        for (int i = jtVinculo.getRowCount() - 1;
            i >= 0; --i) {
            modelovinculo.removeRow(i);
        }

        for (int i = 0;
            i < listavinculo.size();
            i++) {
            modelovinculo.addRow(listavinculo.get(i).getvinculo());
            cont++;
        }
 
    }//GEN-LAST:event_jbVincularActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) jtVinculo.getModel();
        List<Vinculo> list = new ArrayList<Vinculo>();
        ArrayList<Vinculo> nova_list = new ArrayList<Vinculo>();
        linha = jtVinculo.getSelectedRow();
        Object valor = modelo.getValueAt(linha, 0);
        list = arqin3.getTodosVinculos();

        for (int i = 0; i < list.size(); i++) {
            if (!(list.get(i).getPes().getNome().equals(valor))) {
                nova_list.add(list.get(i));
            }
        }
        try {
            arqout3.recadastrar_todos(nova_list);
        } catch (IOException ex) {
            Logger.getLogger(RegistroCarro.class.getName()).log(Level.SEVERE, null, ex);
        }

        modelo.removeRow(linha);
        JOptionPane.showMessageDialog(null, "Vinculo apagado com sucesso");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        Principal princ = new Principal();
        princ.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroCarro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jbVincular;
    private javax.swing.JTable jtCarro;
    private javax.swing.JTable jtPessoa;
    private javax.swing.JTable jtVinculo;
    // End of variables declaration//GEN-END:variables
}
